#!/bin/bash

home="$PWD"

echo ""
echo "BUILD VUE App"
echo ""
cd $home/recovery-mobile-webapp && npm run build

echo ""
echo "DELETE OLD DEPLOY (HEROKU)"
echo ""
rm -rfv $home/herokuServer/www/

echo ""
echo "COPY BUILD WEBAPP INTO HEROKU"
echo ""
cp -a $home/recovery-mobile-webapp/dist $home/herokuServer/www

echo ""
echo "PUSH TO HEROKU"
echo ""
cd $home
echo "git subtree push --prefix herokuServer heroku master"

cd $home
